spring.application.name=pawsaver
server.port=8080

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/pawsaver
spring.datasource.username=postgres
spring.datasource.password=admin

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=pawsaver-super-secret-key-that-is-long-enough-for-hs256-algorithm
jwt.expiration=86400000


# Gemini AI
gemini.api.key=AIzaSyCsvBY6F21eHrD1tGbH2JCALfyVeKX9Lv0
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-flash-latest:generateContent

# File upload settings
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Folder where images will be saved on your computer
app.upload.dir=uploads/animal-reports